version: '2'
services:
  #DB server (MySQL)
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports: 
      - ${DB_PORT_HOST}:${DB_PORT}
  #Application + Webserver
  app:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./testapp.com:/var/www/testapp.com
    ports:
      - ${APP_PORT_HOST}:${APP_PORT}
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
